#!/bin/sh

echo convert holide library dk files to coq files ...

cd libraries/holide

echo convert dk files to v files ...
for f in *.dk
do
    echo $f ...
    b=`basename $f .dk`
    dune exec -- lambdapi export -o coq $b.dk > $b.v || exit 1
done

echo patch hol.v ...
awk -f ../holide.awk hol.v > /tmp/hol.v
cat ../holide.v /tmp/hol.v > hol.v

echo rename files ...
for f in *.v
do
    awk -f ../holide.awk $f > /tmp/$f
    mv -f /tmp/$f $f
    g=`echo $f | sed -e 's/-/_/g'`
    if test "$f" != "$g"
    then
        echo rename $f into $g
        mv $f $g
    fi
done

cd ../..
