(** Translate the parser-level AST to Lean.

There are two modes:

- raw_lean: translation of the AST as it is (the lambda-pi-calculus is a
  subsystem of Lean if we ignore rules).

- stt_lean: translation of the AST as an encoding in simple type theory. The
  encoding can be specified through a lambdapi file with the option
  --encoding. A map giving the number of type variables of each function
  symbol can be given as a .tvs file (as generated by hol2dk) with the option
  --arities.

In both modes, a renaming map can be provided with the option --renaming to
rename some identifiers.
*)

open Lplib open Extra
open Common open Pos open Error
open Parsing open Syntax
open Stt

let typ_arity h =
  match h.elt with
  | P_Iden({elt=(_,sym_name);_},true) when !stt ->
      begin
        match StrMap.find_opt sym_name !tvs_map with
        | None -> 0
        | Some n -> n
      end
  | _ -> 0

(** Translation of terms. *)

let rec term oc t =
  (*if Logger.log_enabled() then
    log "pp %a" (*Pos.short t.pos*) Pretty.term t;*)
  match t.elt with
  | P_Meta _ -> wrn t.pos "TODO"; assert false
  | P_Patt _ -> wrn t.pos "TODO"; assert false
  | P_Expl _ -> wrn t.pos "TODO"; assert false
  | P_Type -> string oc "Type"
  | P_Wild -> char oc '_'
  | P_NLit _ -> wrn t.pos "TODO"; assert false
  | P_SLit _ -> wrn t.pos "TODO"; assert false
  | P_Iden(qid,b) ->
      if b then char oc '@';
      if !stt then
        match QidMap.find_opt qid.elt !map_erased_qid with
        | Some s -> string oc s
        | None -> qident oc qid
      else qident oc qid
  | P_Arro(u,v) -> arrow oc u v
  | P_Abst(xs,u) -> abst oc xs u
  | P_Prod(xs,u) -> prod oc xs u
  | P_LLet(x,xs,a,u,v) ->
    string oc "let "; ident oc x; params_list oc xs; typopt oc a;
    string oc " := "; term oc u; string oc " in "; term oc v
  | P_Wrap u -> term oc u
  | P_Appl _ ->
      let default h ts =
        paren oc h; char oc ' ';
        let ts =
          let n = typ_arity h in
          if n <= 0 then ts else
            let l1,l2 = List.cut ts n in
            l1 @ List.init (n-1) (fun _ -> P.wild) @ l2
        in
        list paren " " oc ts
      in
      app t default
        (fun h ts expl builtin ->
          match !use_notations, !use_implicits && not expl, builtin, ts with
          | _, _, (El|Prf), [u] -> term oc u
          | _, _, (Arr|Imp), [u;v] -> arrow oc u v
          | _, _, All, [_;{elt=P_Wrap({elt=P_Abst([_] as xs,u);_});_}]
          | _, true, All, [{elt=P_Wrap({elt=P_Abst([_] as xs,u);_});_}]
            -> prod oc xs u
          | _, _, Ex, [_;{elt=P_Wrap({elt=P_Abst([x],u);_});_}]
          | _, true, Ex, [{elt=P_Wrap({elt=P_Abst([x],u);_});_}] ->
              string oc "∃ "; raw_params oc x; string oc ", "; term oc u
          | true, _, Eq, [_;u;v]
          | true, true, Eq, [u;v] -> paren oc u; string oc " = "; paren oc v
          | true, _, Or, [u;v] -> paren oc u; string oc " ∨ "; paren oc v
          | true, _, And, [u;v] ->  paren oc u; string oc " ∧ "; paren oc v
          | true, _, Not, [u] -> string oc "¬ "; paren oc u
          | _ -> default h ts)

and arrow oc u v = paren oc u; string oc " -> "; term oc v
and abst oc xs u =
  string oc "fun"; params_list_in_abs oc xs; string oc " => "; term oc u
and prod oc xs u =
  string oc "∀"; params_list_in_abs oc xs; string oc ", "; term oc u

and paren oc t =
  let default() = char oc '('; term oc t; char oc ')' in
  match t.elt with
  | P_Arro _ | P_Abst _ | P_Prod _ | P_LLet _ | P_Wrap _ -> default()
  | P_Appl _ ->
      app t (fun _ _ -> default())
        (fun _ ts _ builtin ->
          match builtin, ts with
          | (El|Prf), [u] -> paren oc u
          | _ -> default())
  | _ -> term oc t

and raw_params oc (ids,t,_) = param_ids oc ids; typopt oc t

and params oc ((ids,t,b) as x) =
  match b, t with
  | true, _ -> char oc '{'; raw_params oc x; char oc '}'
  | false, Some _ -> char oc '('; raw_params oc x; char oc ')'
  | false, None -> param_ids oc ids

and top_params oc ((ids,a,_) as x) =
  params oc x;
  match a with
  | Some{elt=P_Iden(id,_);_} ->
    begin
      match QidMap.find_opt id.elt !map_qid_builtin with
      | Some Set ->
        let nonempty oc id =
          string oc " [Nonempty "; param_id oc id; char oc ']'
        in List.iter (nonempty oc) ids
      | _ -> ()
    end
  | _ -> ()

and params_list oc = List.iter (prefix " " params oc)

and top_params_list oc = List.iter (prefix " " top_params oc)

and params_list_in_abs oc l =
  match l with
  | [ids,t,false] -> char oc ' '; param_ids oc ids; typopt oc t
  | _ -> params_list oc l

and typopt oc t = Option.iter (prefix " : " term oc) t

(** Translation of commands. *)

let req_mod oc p = string oc "import "; path oc p; string oc "\n"
let open_mod oc p = string oc "open "; path oc p; string oc "\n"

let openings = ref []

let export_types oc p_sym_nam t =
  let rec set_to_type t =            
    begin match t with 
      | {elt=P_Iden(id,_);_} as a  ->
          begin
            match QidMap.find_opt id.elt !map_qid_builtin with
            | Some Set -> ({elt=P_Type;pos=a.pos},(true,1))
            | _ -> (a,(false,0))
          end
      | {elt=P_Arro(u,v);_} as a -> 
          let u' = set_to_type u in 
            if fst (snd u')  then
              let v' = set_to_type v in
                if fst (snd v') then 
                  ({elt=P_Arro(fst u',fst v');pos=a.pos},(true, snd (snd u') + snd (snd v')))
              else (a,(false,0))
            else (a,(false,0))
      | _ -> (t,(false,0))
    end 
  in 
  let p = (set_to_type t) in 
      let t' = fst p in
        term oc t' ;
        if fst (snd p) then 
        begin
          match t' with 
          | {elt=P_Type;_} -> 
            string oc "\n@[instance]\naxiom ne_";ident oc p_sym_nam;
            string oc " : Nonempty " ; ident oc p_sym_nam;
          | {elt=P_Arro(_,_);_} -> 
            string oc "\n@[instance]\naxiom ne_";ident oc p_sym_nam;
              let n = (snd (snd p) - 1) in 
                if n > 0 then 
                  begin
                    string oc " (a0";
                    for i=1 to n-1 do string oc " a" ; string oc (string_of_int i); done;
                    string oc " : Type)";
                    string oc " : Nonempty " ;
                    char oc '(';
                    ident oc p_sym_nam; string oc " a0";
                    for i=1 to n-1 do string oc " a" ; string oc (string_of_int i); done;
                    char oc ')';
                  end
                else ident oc p_sym_nam
          | _ -> ()
        end;
    string oc "\n"

let command oc {elt; pos} =
  begin match elt with
  | P_open(_,ps) -> List.iter (open_mod oc) ps
  | P_require(b,ps) ->
      List.iter (req_mod oc) ps;
      begin
        match b with
        | Some true -> openings := List.rev_append ps !openings
        | _ -> () (*FIXME?*)
      end
  | P_require_as _ -> wrn pos "Command not translated."
  | P_symbol { p_sym_mod; p_sym_nam; p_sym_arg; p_sym_typ; p_sym_trm;
               p_sym_prf=_; p_sym_def } ->
      if not (StrSet.mem p_sym_nam.elt !erase) then
        begin match p_sym_def, p_sym_trm, p_sym_arg, p_sym_typ with
          | true, Some t, _, Some a when List.exists is_lem p_sym_mod ->
            string oc "theorem "; ident oc p_sym_nam;
            top_params_list oc p_sym_arg; string oc " : "; term oc a;
            string oc " := by apply "; term oc t; string oc "\n"
          | true, Some t, _, _ ->
            if List.exists is_opaq p_sym_mod then string oc "opaque "
            else string oc "@[reducible]\nnoncomputable def ";
            ident oc p_sym_nam;
            top_params_list oc p_sym_arg; typopt oc p_sym_typ;
            string oc " := "; term oc t; string oc "\n"
          | false, _, [], Some t ->
            string oc "axiom "; ident oc p_sym_nam; string oc " : ";
            export_types oc p_sym_nam t
          | false, _, _, Some t ->
            string oc "axiom "; ident oc p_sym_nam;
            string oc " : ∀"; top_params_list oc p_sym_arg; string oc ", ";
            term oc t; string oc "\n"
          | _ -> wrn pos "Command not translated."
        end
  | _ -> wrn pos "Command not translated."
  end

let commands oc = Stream.iter (command oc)

let handle_requires s =
  let rec handle_next_elt() =
    let x = Stream.next s in
    match x.elt with
    | P_require(b, ps) ->
        List.iter (req_mod stdout) ps;
        begin
          match b with
          | Some true -> openings := List.rev_append ps !openings;
          | _ -> ()
        end;
        handle_next_elt()
    | _ -> Some x
  in
  try handle_next_elt() with Stream.Failure -> None

let print : string -> ast -> unit = fun file s ->
  let oc = stdout in
  Option.iter (fun s -> string oc ("import "^s^"\n")) !require;
  match handle_requires s with
  | None -> ()
  | Some c ->
  List.iter (open_mod oc) (List.rev !openings);
  string oc "\nnamespace ";
  Option.iter
    (fun s -> string oc
                (try (Filename.chop_extension s)^"."
                 with Invalid_argument _ -> "")) !require;
  string oc (Filename.chop_extension file);
  string oc "\n\n";
  (*to erase style-warnings on generated code*)
  string oc "set_option linter.style.header false\n";
  string oc "set_option linter.style.missingEnd false\n";
  string oc "set_option linter.unusedVariables false\n";
  string oc "set_option linter.style.longLine false\n\n";
  command oc c;
  commands oc s
