(** Translate parser-level Lambdapi commands to Lean.

There are two modes:

- raw_lean: translation of commands as they are

- stt_lean: translation of commands modulo an encoding of simple type theory
specified through a lambdapi file with the option --encoding. A map giving the
number of type variables of each function symbol can be given as a .tvs file
(as generated by hol2dk) with the option --arities.

In both modes, a renaming map can be provided with the option --renaming to
rename some identifiers. *)

open Lplib open Extra
open Common open Pos open Error
open Parsing open Syntax
open Stt

let typ_arity h =
  match h.elt with
  | P_Iden({elt=(_,sym_name);_},true) when !stt ->
      begin
        match StrMap.find_opt sym_name !tvs_map with
        | None -> 0
        | Some n -> n
      end
  | _ -> 0

(** Translation of terms. *)

let rec term oc t =
  (*if Logger.log_enabled() then
    log "pp %a" (*Pos.short t.pos*) Pretty.term t;*)
  match t.elt with
  | P_Meta _ -> wrn t.pos "TODO"; assert false
  | P_Patt _ -> wrn t.pos "TODO"; assert false
  | P_Expl _ -> wrn t.pos "TODO"; assert false
  | P_Type -> string oc "Type"
  | P_Wild -> char oc '_'
  | P_NLit _ -> wrn t.pos "TODO"; assert false
  | P_SLit _ -> wrn t.pos "TODO"; assert false
  | P_Iden(qid,b) -> if b then char oc '@'; qident oc qid
  | P_Arro(u,v) -> arrow oc u v
  | P_Abst(xs,u) -> abst oc xs u
  | P_Prod(xs,u) -> prod oc xs u
  | P_LLet(x,xs,a,u,v) ->
    string oc "let "; ident oc x; params_list oc xs; typopt oc a;
    string oc " := "; term oc u; string oc " ; "; term oc v
  | P_Wrap u -> term oc u
  | P_Appl _ ->
      let default h ts =
        paren oc h; char oc ' ';
        let ts =
          let n = typ_arity h in
          if n <= 0 then ts else
            let l1,l2 = List.cut ts n in
            l1 @ List.init (n-1) (fun _ -> P.wild) @ l2
        in
        list paren " " oc ts
      in
      app t default
        (fun h ts expl builtin ->
          match !use_notations, !use_implicits && not expl, builtin, ts with
          | _, _, (El|Prf), [u] -> term oc u
          | _, _, (Arr|Imp), [u;v] -> arrow oc u v
          | _, _, All, [_;{elt=P_Wrap({elt=P_Abst([_] as xs,u);_});_}]
          | _, true, All, [{elt=P_Wrap({elt=P_Abst([_] as xs,u);_});_}]
            -> prod oc xs u
          | _, _, Ex, [_;{elt=P_Wrap({elt=P_Abst([x],u);_});_}]
          | _, true, Ex, [{elt=P_Wrap({elt=P_Abst([x],u);_});_}] ->
              string oc "∃ "; raw_params oc x; string oc ", "; term oc u
          | true, _, Eq, [_;u;v]
          | true, true, Eq, [u;v] -> paren oc u; string oc " = "; paren oc v
          | true, _, Or, [u;v] -> paren oc u; string oc " ∨ "; paren oc v
          | true, _, And, [u;v] ->  paren oc u; string oc " ∧ "; paren oc v
          | true, _, Not, [u] -> string oc "¬ "; paren oc u
          | _ -> default h ts)

and arrow oc u v = paren oc u; string oc " -> "; term oc v
and abst oc xs u =
  string oc "fun"; params_list_in_abs oc xs; string oc " => "; term oc u
and prod oc xs u =
  string oc "∀"; params_list_in_abs oc xs; string oc ", "; term oc u

and paren oc t =
  let default() = char oc '('; term oc t; char oc ')' in
  match t.elt with
  | P_Arro _ | P_Abst _ | P_Prod _ | P_LLet _ | P_Wrap _ -> default()
  | P_Appl _ ->
      app t (fun _ _ -> default())
        (fun _ ts _ builtin ->
          match builtin, ts with
          | (El|Prf), [u] -> paren oc u
          | _ -> default())
  | _ -> term oc t

and raw_params oc (ids,t,_) = param_ids oc ids; typopt oc t

and params oc ((ids,t,b) as x) =
  match b, t with
  | true, _ -> char oc '{'; raw_params oc x; char oc '}'
  | false, Some _ -> char oc '('; raw_params oc x; char oc ')'
  | false, None -> param_ids oc ids

and top_params oc ((ids,a,_) as x) =
  params oc x;
  match a with
  | Some{elt=P_Iden(id,_);_} ->
    begin
      match QidMap.find_opt id.elt !encoding with
      | Some Set ->
        let nonempty oc id =
          string oc " [Nonempty "; param_id oc id; char oc ']'
        in List.iter (nonempty oc) ids
      | _ -> ()
    end
  | _ -> ()

and params_list oc = List.iter (prefix " " params oc)

and top_params_list oc = List.iter (prefix " " top_params oc)

and params_list_in_abs oc l =
  match l with
  | [ids,t,false] -> char oc ' '; param_ids oc ids; typopt oc t
  | _ -> params_list oc l

and typopt oc t = Option.iter (prefix " : " term oc) t

(** Translation of commands. *)

let req_mod oc p = string oc "import "; path oc p; string oc "\n"
let open_mod oc p = string oc "open "; path oc p; string oc "\n"

let openings = ref []

(** Exports a type constructor after replacing
all occurrences of Set with Type (0).
In that case, it also generates the
corresponding Nonempty instance based on its arity.
*)
let export_types oc p_sym_nam ty =
(*
Replace every occurrence of Set by Type.
Returns:
  - the rewritten type,
  - whether the whole type is a type constructor,
  - the number of Type arguments occurring in the constructor. *)
  let rec normalize_type ty =
    match ty with
    | { elt = P_Iden (id, _); pos } ->
        begin
          match QidMap.find_opt id.elt !encoding with
          | Some Set ->
              ({ elt = P_Type; pos }, true, 1)
          | _ ->
              (ty, false, 0)
        end
    | { elt = P_Arro (lhs, rhs); pos } ->
        let lhs', lhs_ok, lhs_count = normalize_type lhs in
        if not lhs_ok then
          (ty, false, 0)
        else
          let rhs', rhs_ok, rhs_count = normalize_type rhs in
          if rhs_ok then
            ({ elt = P_Arro (lhs', rhs'); pos },
             true,
             lhs_count + rhs_count)
          else
            (ty, false, 0)
    | _ ->
        (ty, false, 0)
  in
  (* Print the parameters of a type constructor:
       a0 a1 ... an *)
  let print_type_parameters n =
    if n > 0 then begin
      string oc "a0";
      for i = 1 to n - 1 do
        string oc " a";
        string oc (string_of_int i)
      done
    end
  in
  (* Print the corresponding axiom of type
  Nonempty and add it as an instance. *)
  let print_nonempty_instance ty arity =
    string oc "\n@[instance]\naxiom ne_";
    ident oc p_sym_nam;
    match ty with
    | { elt = P_Type; _ } ->
        string oc " : ";
        string oc "Nonempty ";
        ident oc p_sym_nam
    | { elt = P_Arro (_, _); _ } ->
        let n = arity - 1 in
        if n > 0 then
        begin
          string oc " (";
          print_type_parameters n;
          string oc " : Type) : ";
          string oc "Nonempty ";
          begin
            string oc "(";
            ident oc p_sym_nam;
            string oc " ";
            print_type_parameters n;
            char oc ')'
          end
        end
        else begin
          string oc " : Nonempty ";
          ident oc p_sym_nam
        end
    | _ -> ()
  in
  let ty', is_type_constructor, arity = normalize_type ty in
  begin
    term oc ty';
    if is_type_constructor then
      print_nonempty_instance ty' arity
  end;
  string oc "\n"

let command oc {elt; pos} =
  begin match elt with
  | P_open(_,_,ps) -> List.iter (open_mod oc) ps
  | P_require(b,ps) ->
      List.iter (req_mod oc) ps;
      begin
        match b with
        | Some true -> openings := List.rev_append ps !openings
        | _ -> () (*FIXME?*)
      end
  | P_require_as(p,i) -> Stt.alias := StrMap.add i.elt p.elt !Stt.alias
  | P_symbol { p_sym_mod; p_sym_kw=_; p_sym_nam; p_sym_arg; p_sym_typ;
               p_sym_trm; p_sym_prf=_; p_sym_def } ->
    if not (is_mapped p_sym_nam.elt) then
        begin match p_sym_def, p_sym_trm, p_sym_arg, p_sym_typ with
          | true, Some t, _, Some a when List.exists is_lem p_sym_mod ->
            string oc "nonrec theorem "; ident oc p_sym_nam;
            top_params_list oc p_sym_arg; string oc " : "; term oc a;
            string oc " := by apply "; term oc t; string oc "\n"
          | true, Some t, _, _ ->
            if List.exists is_opaq p_sym_mod then string oc "opaque "
            else string oc "@[reducible]\nnoncomputable def ";
            ident oc p_sym_nam;
            top_params_list oc p_sym_arg; typopt oc p_sym_typ;
            string oc " := "; term oc t; string oc "\n"
          | false, _, [], Some t ->
            string oc "axiom "; ident oc p_sym_nam; string oc " : ";
            export_types oc p_sym_nam t
          | false, _, _, Some t ->
            string oc "axiom "; ident oc p_sym_nam;
            string oc " : ∀"; top_params_list oc p_sym_arg; string oc ", ";
            term oc t; string oc "\n"
          | _ -> wrn pos "Command not translated."
        end
  | _ -> wrn pos "Command not translated."
  end

let commands oc = Stream.iter (command oc)

let handle_requires cmds =
  let rec handle_next_elt() =
    let cmd = Stream.next cmds in
    match cmd.elt with
    | P_require(b, ps) ->
        List.iter (req_mod stdout) ps;
        begin
          match b with
          | Some true -> openings := List.rev_append ps !openings;
          | _ -> ()
        end;
        handle_next_elt()
    | _ -> Some cmd
  in
  try handle_next_elt() with Stream.Failure -> None

let set_option oc s =
  string oc "set_option "; string oc s; string oc " false\n"

let print : string -> p_commands -> unit = fun file cmds ->
  let oc = stdout in
  Option.iter (fun s -> string oc ("import "^s^"\n")) !require;
  match handle_requires cmds with
  | None -> ()
  | Some cmd ->
    List.iter (set_option oc) ["linter.style.header"
                              ;"linter.style.missingEnd"
                              ;"linter.unusedVariables"
                              ;"linter.style.longLine"];
    string oc "\n";
    List.iter (open_mod oc) (List.rev !openings);
    string oc ("\nnamespace "^Filename.chop_extension file^"\n");
    command oc cmd;
    commands oc cmds
